# Generated by Django 5.2.9 on 2025-12-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pair', models.CharField(max_length=20)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=6)),
                ('buy_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('sell_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('opening_capital', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('profit', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('loss', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14)),
                ('closing_balance', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to='users.tradingaccount')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
