# Generated by Django 5.2.9 on 2025-12-31 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('bank', models.CharField(choices=[('GTB', 'GTBank'), ('ACCESS', 'Access'), ('ZENITH', 'Zenith'), ('UBA', 'UBA'), ('FIRST', 'FirstBank'), ('UNION', 'Union'), ('ECO', 'Ecobank'), ('POLARIS', 'Polaris'), ('KEYSTONE', 'Keystone'), ('STANBIC', 'Stanbic'), ('JAIZ', 'Jaiz'), ('FIDELITY', 'Fidelity'), ('OPAY', 'Opay'), ('PALMPAY', 'PalmPay'), ('MONIEPOINT', 'Moniepoint')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
