# Generated by Django 5.2.9 on 2025-12-31 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deposits', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deposit',
            options={'ordering': ['date', 'created_at']},
        ),
        migrations.AddField(
            model_name='deposit',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='users.tradingaccount'),
            preserve_default=False,
        ),
    ]
