# Generated by Django 5.2.9 on 2025-12-31 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('bank', models.CharField(choices=[('GTB', 'GTBank'), ('ACCESS', 'Access'), ('ZENITH', 'Zenith'), ('UBA', 'UBA'), ('FIRST', 'FirstBank'), ('UNION', 'Union'), ('ECO', 'Ecobank'), ('POLARIS', 'Polaris'), ('KEYSTONE', 'Keystone'), ('STANBIC', 'Stanbic'), ('JAIZ', 'Jaiz'), ('FIDELITY', 'Fidelity'), ('OPAY', 'Opay'), ('PALMPAY', 'PalmPay'), ('MONIEPOINT', 'Moniepoint')], max_length=20)),
                ('capital_before', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('capital_after', models.DecimalField(decimal_places=2, editable=False, max_digits=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to='users.tradingaccount')),
            ],
            options={
                'ordering': ['date', 'created_at'],
            },
        ),
    ]
